# Generated by Django 2.0.1 on 2019-04-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.TextField(default=''),
        ),
    ]
