# Generated by Django 2.0.1 on 2019-04-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.CharField(default='', max_length=300),
        ),
    ]
